#!/bin/sh
java -Xmx720m -Xss1m -cp .:bin/:lib/jdom.jar:lib/isorelax.jar:\
lib/isorelax-jaxp-bridge-1.0.jar:lib/msv.jar:lib/relaxngDatatype.jar:lib/xsdlib.jar \
	edu.northwestern.at.morphadorner.tools.validatexmlfiles.ValidateXMLFiles \
	$1 $2 $3 $4 $5 $6 $7 $8 $9

